import type { Metadata } from "next";
import { Geist, Geist_Mono, Space_Grotesk, Inter } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import SidebarPublic from "@/components/SidebarPublic";

const interHeading = Inter({ subsets: ["latin"], variable: "--font-heading" });

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-sans",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        spaceGrotesk.variable,
        interHeading.variable,
      )}
    >
      <body className="min-h-screen flex flex-col bg-gray-100">
        <Navbar />
        <div className="w-full flex h-[calc(100dvh-76px)]">
          <SidebarPublic />
          <div className="w-full h-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
