import type { Metadata } from "next";
import { Geist, Geist_Mono, Space_Grotesk, Inter } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import SidebarPublic from "@/components/SidebarPublic";
import { cookies } from "next/headers";
import { getUserProfile } from "@/lib/api";

const interHeading = Inter({ subsets: ["latin"], variable: "--font-heading" });

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-sans",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  let token = undefined;

  // Next 15 compatibility check for cookies()
  if (typeof cookieStore.then === "function") {
    const resolvedCookies = await cookieStore;
    token = resolvedCookies.get("access_token")?.value;
  } else {
    // @ts-ignore
    token = cookieStore.get("access_token")?.value;
  }

  let user = null;
  if (token) {
    try {
      const res = await getUserProfile(token);
      if (res?.data) {
        user = res.data;
      }
    } catch (e) {
      console.error(e);
    }
  }

  return (
    <html
      lang="en"
      className={cn(
        "h-[100dvh]",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        spaceGrotesk.variable,
        interHeading.variable,
      )}
    >
      <body className="h-[100dvh] flex flex-col bg-gray-100 overflow-hidden">
        <Navbar user={user} />
        <div className="w-full flex flex-1 h-[calc(100dvh-76px)] gap-2 overflow-hidden">
          <SidebarPublic user={user} />
          <div className="w-full h-full flex-1 p-2 overflow-auto">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
